### ISSUE TITLE
Product that are deleted in the back end when still in a users cart

### ISSUE THREAD

**Issue by steveclarkcouk** [jigoshop/jigoshop#1011]
I have found an issue whilst developing a client jigoshop system. I have items in my cart which have now been deleted from the back end which renders the following error:

```
Fatal error: Call to a member function get_price_excluding_tax() on a non-object in /chroot/home/skinnycl/skinny.clark-studios.co.uk/html/wp-content/plugins/jigoshop/classes/jigoshop_cart.class.php on line 82
```

I found to clear the cart I had to call jigoshop_cart::empty_cart() and remove self::$tax->init_tax(); from reset_totals().

**Comment by digitalcrate** [comment]
Hey, this fix doesnt seem to work for me in v1.16.  As you mention, there is already a shortcode to empty the cart, but I still have the error you have stated above.  I had deactivated the plug in but now I get this error whenever I try to activate the plug in now???  I'm confused as to whats causing the issue and how to fix it.  Simply removing the self::tax->init_tax(); doesnt change anything, simply results in the same error message.  Did you actually manage to get your cart cleared?  Could you shed some light on what I might be doing wrong?
