### ISSUE TITLE
divided by zero

### ISSUE THREAD

**Issue by Alejandro26** [jigoshop/jigoshop#1031]
Category list product
li class="product &lt;br /&gt;
&lt;b&gt;Warning&lt;/b&gt;:  Division by zero in &lt;b&gt;public_html/wp-content/plugins/jigoshop/templates/loop-shop.php&lt;/b&gt; on line &lt;b&gt;36&lt;/b&gt;&lt;br /&gt;
last&lt;br /&gt;
&lt;b&gt;Warning&lt;/b&gt;:  Division by zero in &lt;b&gt;public_html/wp-content/plugins/jigoshop/templates/loop-shop.php&lt;/b&gt; on line &lt;b&gt;36&lt;/b&gt;&lt;br /&gt;
first">

**Comment by KrzysztofBorbis** [comment]
Go to: 'Jigoshop Settinhs > Catalog & Pricing > Catalog products per row'
If this option is empty set some value.

**Comment by Alejandro26** [comment]
it's working, thankss!!! :)
