### ISSUE TITLE
Free shipping coupon

### ISSUE THREAD

**Issue by newash** [jigoshop/jigoshop#1032]
Hey lads,

It's a UX problem about the free shipping coupons.
If a user is adding a free shipping coupon to its cart the "free shipping" option will be available for him. Only it's not selected by default, but whatever shipping he already has in his `jigoshop_session` keeps selected. So a second step is needed to actually change to the "free shipping" option.

You might think it's not an issue and it hasn't came up with myself when I was building our shop. I added the coupon, saw that I still had the old shipping option and changed it.

Unfortunately it's not that obvious to some of our users, and even if looks like a trivial problem: if it's indeed a problem for them, it's going to be a problem for us.

I'm not sure if it's the best solution but the chosen shipping could be deleted from `jigoshop_session` if a free shipping coupon is added in `jigoshop_cart::add_discount`. OK, the user would loose his carefully selected shipping option but he would be just adding a coupon to make something cheaper, so it might not be a real issue.

What do you think?

**Comment by megawebmaster** [comment]
Well, I think that if user adds coupon for free shipping (and I suppose free shipping only?) we could change and select free shipping option. Although I'm not sure how to solve this properly so that user could decide what to do. 

However your solution has really nice advantage - in case user forgets to select new shipping method he won't be able to process checkout (will get information about invalid shipping method).

Maybe removing shipping method and adding notice "Free shipping coupon applied. Please select appropriate shipping method to your order" will solve all issues?

**Comment by newash** [comment]
I don't see if "free shipping only" or "also free shipping" would make any difference, nor from the coding neither from the users' side, but correct me if it does.

I haven't actually debugged it but from the code of `jigoshop_shipping::calculate_shipping()` it looks that on the cart page if `jigoshop_session::instance()->chosen_shipping_method_id` is not set it will go and set the cheapest method -- in this case the free shipping.
(`shortcodes/cart.php` >> `jigoshop_cart::calculate_totals()` >> `jigoshop_shipping::calculate_shipping()` >> `self::get_cheapest_method()`)

So if I'm right, by deleting the shipping method would result the free shipping selected. I don't see it as a problem but if you think it's not a good idea (remember my objection about automatically removing the coupon if the wrong payment was selected... hehe) then showing the notice would also be fine with me.

**Comment by newash** [comment]
bump! ;)

**Comment by PaulPreston** [comment]
Can you please confirm if this is still an issue?

**Comment by newash** [comment]
I can confirm that it still is.

**Comment by PaulPreston** [comment]
I have assigned it to Krzysztof who will look into it tomorrow.

**Comment by newash** [comment]
Maybe only we have the dumbest customers on the planet, but it's a constantly annoying issue.
Even if we tell them, that it won't be selected automatically and they have to click here-and-there to actually have the free shipping, 90% of them misses that.
And to keep them happy (they are the ones paying) I need to adjust their order manually on the admin screen. And re-send the confirmation email.
So it's far from being optimal now.

**Comment by newash** [comment]
Bump! (sorry, for being annoying with this, but I also cannot believe it is an issue only for me...)

**Comment by newash** [comment]
bump No.3...

**Comment by newash** [comment]
bump No.4...
Is anyone out there?

**Comment by KrzysztofBorbis** [comment]
Hi newash,

Sorry for no response for so long. Our current priority is Jigoshop 2, I'll try to implement this before next update.

**Comment by newash** [comment]
Nice!! I tested it quickly and it was working.
Big thanks!
