### ISSUE TITLE
Missing from emails: bank payment details

### ISSUE THREAD

**Issue by newash** [jigoshop/jigoshop#1033]
I really don't know lads...
How people are using your plugin? No one has been missing this since 1.13?

Anyway, I do. :) *It was essential* because if people chose bank transfer they had all the data in their email for the transfer.

Now I haven't made a pull request because I'm not totally sure about the best solution but this is my proposal:

- `jigoshop_payment_gateway` class needs a method, say `get_transfer_details` that returns an empty string
- a new email shortcode is registered for this in `jigoshop_emails.php` that based on `$order->payment_method` calls this method of the appropriate subclass
- `jigoshop_bank_transfer` overrides this method and returns whatever its `get_bank_details` method returns

This way it could be general and extendable.

**Comment by KrzysztofBorbis** [comment]
I added it in other way. In 1.16 this feature will be awalible by using construction like this:

[is_bank_transfer][bank_info][/is_bank_transfer] or

[is_bank_transfer] You chose bank transfer as payment method for this order, bank transer details are below:<br/>[bank_info][else] You chose [payment_method] as payment method for this order [/is_bank_transfer]

**Comment by newash** [comment]
If it does the same job, it's perfect :)

Thanks!
