### ISSUE TITLE
Multiple Shortcodes Not Showing On Page

### ISSUE THREAD

**Issue by SimpleBeadPatterns** [jigoshop/jigoshop#1039]
Hi,

Since updating Jigoshop, if I try to have several shortcodes on the same page, the first shortcode list of products shows up, but any other following shortcodes do not show up (this used to work for me before updating).  This is the shortcode I am using [products ids="1, 2, 3"].

After a lot of research, I found that using the jigoshop_templates.php from this website (http://forum.jigoshop.com/discussions/problems/10929-shortcodes-not-working) fixed the problem but created a fatal error on my shopping cart.

Fatal error: Call to undefined function jigoshop_locate_template() ... wp-content/plugins/jigoshop/jigoshop.php on line 1099

Here is my system info:
### WordPress Environment ###

Home URL: http://simplebeadpartners.com
Site URL: http://simplebeadpartners.com
Jigoshop Version: 1.17.3
Jigoshop Database Version: 1503180
Log Directory Writable: ✕ 

WP Version: 4.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.3.29
PHP Post Max Size: 999 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.42
eAccelerator: ✕
APC: ✕
OpCache: ✕
Short Open Tag: ✔
Allow URL fopen: ✔
Session: ✔
Cookie Path: /
Save Path: /tmp
Use Cookies: ✔
Use Only Cookies: ✔
Max Upload Size: 999 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Active Plugins (21) ###

Anti-spam: by webvitaly – 3.5
Display Posts Shortcode: by Bill Erickson – 2.4
Enable Media Replace: by Måns Jonasson – 3.0.3
Enhanced Text Widget: by Boston Dell-Vandenberg – 1.4.4
Image Widget: by Modern Tribe
Inc. – 4.1

Intuitive Custom Post Order: by hijiri – 3.0.4
Jigoshop Admin Bar Addition: by David Decker - DECKERWEB – 1.8
Jigoshop - All in One SEO Pack: by Visser Labs – 1.0
Jigoshop Basic Bundle Shipping: by polevaultweb – 1.0.2
Jigoshop - Meta Tags: by Jigowatt – 1.1
Jigoshop Table Rate Shipping: by Jigoshop – 3.3.4
Jigoshop: by Jigoshop Limited – 1.17.3
Log Out Shortcode: by OM4 – 1.0.3
MailChimp: by MailChimp and Crowd Favorite – 1.4.2
Menu Image: by Alex Davyskiba aka Zviryatko – 2.4
Pinterest "Pin It" Button Lite: by Phil Derksen – 2.0.8
Quick Page/Post Redirect Plugin: by Don Fischer – 5.0.6
Regenerate Thumbnails: by Viper007Bond – 2.2.4
Slideshow: by StefanBoonstra – 2.2.21
Theme My Login: by Jeff Farthing – 6.3.11
Ultimate Follow Me Plugin by Free Blog Factory: by Free Blog Factory – 1.3.3

### Settings ###

Taxes Enabled: ✔
Shipping Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### Jigoshop Pages ###

Shop Base: #219 - /shop-3/
Cart: #220 - /cart-3/
Checkout: #226 - /checkout-3/
Pay: #227 - /checkout-3/pay/
Thanks: #228 - /checkout-3/thanks/
My Account: #222 - /my-account-3/
Edit Address: #223 - /my-account-3/edit-address/
View Order: #225 - /my-account-3/view-order/
Change Password: #224 - /my-account-3/change-password/
Track Order: #221 - /order-tracking-3/
Terms: Page not set

### Taxonomies ###

Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
virtual (virtual)

### Theme ###

Name: Skeleton
Version: 1.6
Author URL: http://www.simplethemes.com
Child Theme: ✕ – If you're modifying Jigoshop or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
Jigoshop Support: Not Declared

### Templates ###

Overrides: skeleton/archive-product.php
skeleton/checkout/index.php
skeleton/checkout/pay_for_order.php
skeleton/index.php
skeleton/loop-shop.php
skeleton/jigoshop/product_taxonomy.php
skeleton/single-product-reviews.php
skeleton/jigoshop/single-product.php
skeleton/jigoshop/taxonomy-product_cat.php
skeleton/jigoshop/taxonomy-product_tag.php

Thank you for your help.

**Comment by PaulPreston** [comment]
This issue was resolved in Jigoshop 1.17.4 and onwards
