### ISSUE TITLE
Thoughts on HTML email styling

### ISSUE THREAD

**Issue by newash** [jigoshop/jigoshop#1044]
Wow! I wouldn't say it was super-fast, but I managed to update to the latest Jigoshop this weekend. With the HTML emails and everything.

You might be well aware of this, but these new HTML emails are not being shown properly everywhere.
I only tested on web Gmail, Android Gmail app and whatever email app an iPhone has.

- Gmail + iPhone apps: inline styling is OK, but all styles defined in the header are discarded
- web Gmail: inline styling is OK, styles from the header are selectively discarded. These are the styles Gmail takes out:
 - "a" in all its variations (but not if the target is something else and "a" just an additional part of the selector)
 - class information is removed from HTML nodes, so any references to classes won't work, though the style definitions are not removed

I can see three possible places of improvements here:

- change selectors with class references to more complicated selectors that don't contain any class names. It would be an improvement for at least web Gmail (and possibly to other clients, I don't know)
- put inline styles into email post contents. You might not want to do that, since that makes those contents messy, but it's HTML emailing, so it's not about anything nice and clean ;)
- put inline styles into [items.php](/jigoshop/jigoshop/blob/master/templates/emails/items.php) so at least the order contents table would be properly styled in every client. << I think this should be definitely done regardless of the previous two.

Kind regards,

**Comment by KrzysztofBorbis** [comment]
It should be done in 1.17.7

**Comment by PaulPreston** [comment]
Krzysztof: when do you expect to have it ready?
