### ISSUE TITLE
coupon hook problem

### ISSUE THREAD

**Issue by newash** [jigoshop/jigoshop#1049]
Lads,

I've just caught this when I wanted to figure why was my stuff hooked onto [jigoshop_get_shop_coupon_data](https://github.com/jigoshop/jigoshop/blob/master/classes/jigoshop_coupons.class.php#L127) acting weird.
It turned out that if the cart already contained any coupon then my function was not called at all.
And it was because of cart_total calculation on jigoshop_init():

It goes to calculate discounts therefore initializes the static [$coupons](https://github.com/jigoshop/jigoshop/blob/master/classes/jigoshop_coupons.class.php#L22) attribute **before** a different plugin or the active theme would have the chance to load itself up and hook onto "jigoshop_get_shop_coupon_data". Really annoying, especially because it's not obvious from Jigoshop code that you should be careful with this hook.

Here is the stacktrace of what's happening when the cart contains coupons:

```
#0  JS_Coupons::get_coupons() called at [.../wp-content/plugins/jigoshop/classes/jigoshop_coupons.class.php:143]
#1  JS_Coupons::get_coupon(...) called at [.../wp-content/plugins/jigoshop/classes/jigoshop_cart.class.php:196]
#2  jigoshop_cart::calculate_product_discounts_total(...) called at [.../wp-content/plugins/jigoshop/classes/jigoshop_cart.class.php:82]
#3  jigoshop_cart::calculate_cart_total() called at [.../wp-content/plugins/jigoshop/classes/jigoshop_cart.class.php:49]
#4  jigoshop_cart->__construct(Array ()) called at [.../wp-content/plugins/jigoshop/classes/abstract/jigoshop_singleton.class.php:34]
#5  Jigoshop_Singleton::instance() called at [.../wp-content/plugins/jigoshop/jigoshop.php:360]
#6  jigoshop_init()
#7  call_user_func_array(jigoshop_init, Array ([0] => )) called at [.../wp-includes/plugin.php:496]
#8  do_action(init) called at [.../wp-settings.php:353]
#9  require_once(.../wp-settings.php) called at [.../wp-config.php:107]
#10 require_once(.../wp-config.php) called at [.../wp-load.php:37]
#11 require_once(.../wp-load.php) called at [.../wp-admin/admin-ajax.php:22]
```

Take care,

**Comment by KrzysztofBorbis** [comment]
How are you using 'jigoshop_get_shop_coupon_data' ? I checked it and for me it works good. Did I miss something?

**Comment by newash** [comment]
Well... I have a plugin and I initialize it on the 'jigoshop_initialize_plugins' hook. During that I attach a function onto 'jigoshop_get_shop_coupon_data' to add an extra attribute to the coupon value array.

This thing totally works fine if you start with a cart with no coupons and you add a new coupon. Then my function is called because the coupon array is initialized during some validation stuff.
But from then on (since the cart already contains a coupon) the static array $coupons gets initialized - as you can see - in jigoshop init very early. Before 'jigoshop_initialize_plugins' is called.

See lines 360 (where coupon array init happens) and 376 in *jigoshop.php*.

**Comment by KrzysztofBorbis** [comment]
I see. There should be a action call on top of the jigoshop_init function, 'before_jigoshop_init' or something similar.

**Comment by newash** [comment]
:) Personally I'd put the 'jigoshop_initialize_plugins' call before line 358 so it would solve this and also my previous closed issue #1042.
But I don't know what complications/bugs/issues it'd possibly cause.

**Comment by KrzysztofBorbis** [comment]
`jigoshop_initialize_plugins` was created for modules located in `jigoshop/plugins` diredtory. So at this moment it will cause a problems with cart favicon counter.

Also I think I'll add something more than `before_jigoshop_init` action call, to avoid this situation in future :) I'll add action and filter call in Jigoshop_Singleton 

```php
public static function instance() {
   	$class = apply_filters('jigoshop_called_class', get_called_class());

    	if ( isset( self::$instance[$class] ) ) return self::$instance[$class];

    	$args = func_get_args();

    	do_action('jigoshop_before_'.$class.'_class_init', $args);

    	self::$instance[$class] = new $class( $args );

    	return self::$instance[$class];
    }
```

**Comment by newash** [comment]
Cool.
