### ISSUE TITLE
Jigoshop 2.0 (products for free / Order actions)

### ISSUE THREAD

**Issue by 19Bobo90** [jigoshop/jigoshop#1078]
Hi,

we are using Jigoshop in our association for tool rental and many tools are for free.

I tested v2.0 (Jigoshop2-master) yesterday and now we are using v1.18.1 angain because of the following problems:

- In Jigoshop 2.0 isn't a **"Add to cart"-Button** when you set the price to **0€** (only "Price Not Announced" appears). Is it possible that you provide an option (a: show "Price not announced" + no cart-button / b: show "Free" + cart-button)?

- In v1.x we are able to edit orders. We use the option "Restore stock" when the tools return. I can't find the "**Order Actions**" in v2.0. Is it possible to integrate the "order actions" in v2.0?

Best regards
Robert

**Comment by kkasowski** [comment]
Hi,

In future please add next issues to Jigoshop2 (Jigoshop eCommerce) repository.

Your issues have been solved :) see commits below.

https://github.com/jigoshop/Jigoshop2/commit/059a1f9f2f394465863001078d92e88fb569d783
https://github.com/jigoshop/Jigoshop2/commit/03492a9ee107bccc0395365fa6dc4176a79a3b70
